package org.doraemon.framework.exception;

import org.junit.Test;

/**
 * @description: 描述
 * @author: fengwenping
 * @date: 2020-07-05 23:23
 */
public class BusinessExceptionTest {

    @Test
    public void throwNewException() {
    }

    @Test
    public void testThrowNewException() {
    }

    @Test
    public void testThrowNewException1() {
    }

    @Test
    public void isTrue() {
    }

    @Test
    public void testIsTrue() {
    }

    @Test
    public void isFalse() {
    }

    @Test
    public void testIsFalse() {
    }

    @Test
    public void isEquals() {
    }

    @Test
    public void testIsEquals() {
    }

    @Test
    public void isNotNull() {
    }

    @Test
    public void testIsNotNull() {
    }

    @Test
    public void isNull() {
    }

    @Test
    public void testIsNull() {
    }

    @Test
    public void isNotEmpty() {
    }

    @Test
    public void testIsNotEmpty() {
    }

    @Test
    public void testIsNotEmpty1() {
    }

    @Test
    public void testIsNotEmpty2() {
    }

    @Test
    public void testIsNotEmpty3() {
    }

    @Test
    public void testIsNotEmpty4() {
    }

    @Test
    public void isInstanceOf() {
    }

    @Test
    public void testIsInstanceOf() {
    }

    @Test
    public void isAssignableFrom() {
    }

    @Test
    public void testIsAssignableFrom() {
    }
}